language: node_js
node_js: "8"
branches:
  only:
  - master
cache:
  directories:
    - node_modules
before_install:
  - mysql -e 'CREATE DATABASE testdb;'
notifications:
  slack: ucforlfsfft11-c0g7683:veEibqRjNenvzCr0o2n6Tten